/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IMaterialSymbolsLightClose: typeof import('~icons/material-symbols-light/close')['default']
    IMaterialSymbolsLightHomeOutline: typeof import('~icons/material-symbols-light/home-outline')['default']
    IMaterialSymbolsLightPlayingCardsSharp: typeof import('~icons/material-symbols-light/playing-cards-sharp')['default']
    IMdiCardsPlaying: typeof import('~icons/mdi/cards-playing')['default']
    IMdiLightPlus: typeof import('~icons/mdi-light/plus')['default']
    IRivetIconsHappy: typeof import('~icons/rivet-icons/happy')['default']
    ISolarHamburgerMenuLinear: typeof import('~icons/solar/hamburger-menu-linear')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
