name: "Run TODO to Issue"
on: ["push"]
jobs:
  build:
    runs-on: "ubuntu-latest"
    permissions:
      issues: write
    steps:
      - uses: "actions/checkout@v4.2.2"
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v5.1.10"
